import { bookUrl } from "../data";
import { FaInstagram, FaLinkedinIn } from "react-icons/fa6";
import { getSiteContent } from "../cms";

type SocialLink = {label: string; Icon: typeof FaInstagram; href: string};

function SocialLinks({ links, mobile = false }: { links: SocialLink[]; mobile?: boolean }) {
  return <div className={mobile ? "mobile-social-links" : "header-social-links"} aria-label="Social media">{links.map((social) => <a key={social.label} href={social.href} target="_blank" rel="noreferrer" aria-label={`ReviTouch on ${social.label}`} title={social.label}>{mobile ? social.label : <social.Icon aria-hidden="true" />}</a>)}</div>;
}

export async function Header(){const {general}=await getSiteContent();const links=[{label:"Instagram",Icon:FaInstagram,href:general.instagramUrl},{label:"LinkedIn",Icon:FaLinkedinIn,href:general.linkedinUrl}].filter((link)=>link.href);return <header className="site-header"><a className="brand" href="/" aria-label="ReviTouch home"><img src="/images/logo.png" alt="ReviTouch Massage Therapy" /></a><nav aria-label="Main navigation"><a href="/">Home</a><a href="/treatments">Treatments</a><a href="/laser">Laser</a><a href="/about">About</a><a href="/gift-cards">Gift Cards</a><a href="/pricing">Pricing</a><a href="/reviews">Reviews</a><a href="/contact">Contact</a></nav><div className="header-actions"><SocialLinks links={links} /><a className="button small header-book" href={bookUrl}>Book now</a><details className="mobile-menu"><summary aria-label="Open navigation menu"><span /><span /><span /></summary><div className="mobile-menu-panel"><nav aria-label="Mobile navigation"><a href="/">Home</a><a href="/treatments">Treatments</a><a href="/laser">Laser services</a><a href="/about">About</a><a href="/gift-cards">Gift Cards</a><a href="/pricing">Pricing</a><a href="/reviews">Reviews</a><a href="/contact">Contact</a></nav><SocialLinks links={links} mobile /><a className="mobile-menu-book" href={bookUrl}>Book now</a></div></details></div></header>}
export async function Footer(){const {general}=await getSiteContent();return <footer><div className="footer-content"><a className="footer-brand" href="/"><img src="/images/logo.png" alt="ReviTouch" /></a><div><p>{general.footerDescription}</p><p>{general.copyright}</p></div><div className="footer-links"><a href="/treatments">Massage</a><a href="/laser">Laser</a><a href="/about">About</a><a href="/gift-cards">Gift Cards</a><a href="/contact">Contact</a></div></div><div className="announcement footer-announcement">{general.announcement} <a href={`tel:${general.phoneLink}`}>Call or text {general.phoneDisplay}</a></div></footer>}
export function MobileBar(){return null}
export function PageShell({children}:{children:React.ReactNode}){return <main><Header />{children}<Footer /><MobileBar /></main>}
