export const bookUrl = "https://www.revitouch.com/book-online";
export const services = [
  { name: "Sports Massage", image: "/images/sports.jpg", text: "Targeted treatment for flexibility, recovery, trigger points, and specific areas of discomfort.", detail: "Sports massage combines focused pressure, trigger-point therapy, and myofascial techniques. It is designed for active bodies, desk-bound bodies, and anyone looking to improve mobility or address a stubborn problem area." },
  { name: "Deep Tissue Massage", image: "/images/deep-tissue.jpg", text: "Slow, focused movement and firm pressure designed to reach deeper layers of muscle tissue.", detail: "Deep tissue work uses deliberate movement and firmer pressure to address persistent tension. Your therapist adjusts throughout the session so the treatment remains productive and within your comfort level." },
  { name: "Swedish Massage", image: "/images/hero.jpg", text: "A restorative full-body treatment that supports circulation, relaxation, and overall wellbeing.", detail: "Swedish massage uses flowing soft-tissue techniques to encourage circulation and a deep sense of ease. It is an excellent choice when stress relief, rest, and overall wellbeing are your priorities." },
  { name: "Cupping Therapy", image: "/images/cupping.jpg", text: "Therapeutic suction that can help ease stiffness, inflammation, and back discomfort.", detail: "Cupping uses gentle suction to support circulation and create space in tight tissue. It can be used as a focused 20-minute treatment or incorporated into a broader care plan." },
  { name: "Hot Stone Massage", image: "/images/deep-tissue.jpg", text: "Warm stones and skilled touch help soften tension and encourage profound relaxation.", detail: "Heated stones bring warmth to the muscles while your therapist works with calm, considered pressure. This hour-long treatment is designed for deep relaxation and muscular ease." },
  { name: "Prenatal Massage", image: "/images/hero.jpg", text: "Supportive, comfortable care tailored to the changing needs of pregnancy.", detail: "Prenatal massage is adapted for comfort and support, with positioning and pressure selected around your stage of pregnancy and individual needs." },
];
export const appointments = [["15 min Treatment", "15 min", "$40"],["Cupping Therapy", "20 min", "$40"],["30 min Treatment", "30 min", "$80"],["45 min Treatment", "45 min", "$130"],["60 min Treatment", "60 min", "$160"],["Prenatal Massage", "60 min", "$180"],["Hot Stone Massage", "60 min", "$190"],["75 min Treatment", "75 min", "$200"],["90 min Treatment", "90 min", "$235"]];
