import { Footer, Header, MobileBar } from "./components/SiteChrome";
import { bookUrl, services } from "./data";

export default function Home() {
  return <main><Header />
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Massage therapy, made for real life</p><h1>Feel better.<br /><em>Move freely.</em></h1><p className="lede">Personalized, restorative treatments that fit your schedule—from a focused 15-minute reset to a full session of hands-on care.</p><div className="actions"><a className="button" href={bookUrl}>Book your treatment</a><a className="text-link" href="/treatments">Explore services <span>→</span></a></div><div className="trust-row"><span><b>12+</b> years of experience</span><span><b>4.9 ★</b> client rating</span><span><b>Women</b> owned business</span></div></div><div className="hero-visual"><span className="shape shape-one" /><span className="shape shape-two" /><img src="/images/hero.jpg" alt="Relaxing personalized massage treatment at ReviTouch" /><div className="floating-card"><strong>Care that meets you</strong><span>Focused treatments. Personal attention.</span></div></div></section>

    <section className="intro"><div className="intro-lead"><p className="eyebrow">The ReviTouch promise</p><h2>Treatments that fit your schedule.</h2><p>Every session is shaped around what your body needs today.</p><a className="soft-link" href="/about">Meet ReviTouch →</a></div><div className="intro-grid"><div><strong>15–90</strong><span>minute treatments</span></div><div><strong>4+</strong><span>specialized techniques</span></div><div><strong>1:1</strong><span>personalized care</span></div></div></section>

    <section className="home-information"><div className="information-heading"><p className="eyebrow">Why massage therapy?</p><h2>Your body communicates. We help you listen.</h2><p>Discomfort can come from training, long hours at a desk, repetitive movement, pregnancy, stress, or simply moving through a busy life. Personalized massage can help you understand those signals and respond with care.</p></div><div className="information-grid"><article><span>01</span><h3>Ease persistent tension</h3><p>Focused hands-on work can help soften tight tissue and address areas that feel restricted or overworked.</p></article><article><span>02</span><h3>Support movement</h3><p>Treatment can encourage flexibility, circulation, and a more comfortable range of motion.</p></article><article><span>03</span><h3>Create room to reset</h3><p>A session gives your nervous system time to slow down while your therapist focuses fully on what your body needs.</p></article></div></section>

    <section className="home-preview"><div className="section-head"><div><p className="eyebrow">Treatment overview</p><h2>Different techniques, one personal approach.</h2></div><p>Your therapist can focus on a specific concern or create a broader restorative session. Explore the treatment types to understand which may be the best starting point.</p></div><div className="preview-grid">{services.slice(0,3).map((service) => <a className="preview-card" href="/treatments" key={service.name}><img src={service.image} alt="" /><div><h3>{service.name}</h3><p>{service.text}</p><span>Understand this treatment →</span></div></a>)}</div><a className="button preview-button" href="/treatments">Explore all treatments</a></section>

    <section className="home-story"><div><p className="eyebrow light">Care with intention</p><h2>Your appointment should feel personal from the start.</h2><p>We listen first, then shape the pressure, techniques, and session length around your body and your goals.</p><a className="button light-button" href="/about">Our approach</a></div><img src="/images/sports.jpg" alt="Targeted professional massage treatment" /></section>

    <section className="home-laser"><img src="/images/laser-hero.jpg" alt="Professional laser hair removal treatment at ReviTouch" /><div><p className="eyebrow">Also at ReviTouch</p><h2>Laser hair removal and skin treatments.</h2><p>Explore Cynosure Elite+ laser hair removal, photo rejuvenation, laser facials and dark spot treatments—with a free consultation to personalize your plan.</p><a className="button" href="/laser">Explore laser services</a></div></section>

    <section className="home-review"><p className="stars">★★★★★</p><blockquote>“Every session feels intentional, professional, and completely tailored to what I need that day.”</blockquote><a className="text-link" href="/reviews">Read client stories →</a></section>

    <section className="home-cta"><div><p className="eyebrow">A simple next step</p><h2>Start with the time you have.</h2><p>If ReviTouch feels like the right fit, see current pricing, choose an appointment, or contact us with questions.</p></div><div><a className="button" href={bookUrl}>View availability</a><a className="text-link" href="/pricing">See pricing →</a></div></section>
    <Footer /><MobileBar />
  </main>;
}
